import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.util.List;

public class StaffDashboard extends JFrame {
    private final LoginFrame loginFrame; private final CafeteriaApp app; private final Staff staff; private final JPanel content=new JPanel(new BorderLayout());
    public StaffDashboard(LoginFrame loginFrame,CafeteriaApp app,Staff staff){super("Staff Dashboard • University Cafeteria");this.loginFrame=loginFrame;this.app=app;this.staff=staff;buildUI();showHome();}
    private void buildUI(){setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);setSize(1120,700);setMinimumSize(new Dimension(950,620));setLocationRelativeTo(null);JPanel root=new JPanel(new BorderLayout());root.setBackground(UITheme.BG);root.add(sidebar(),BorderLayout.WEST);root.add(content,BorderLayout.CENTER);setContentPane(root);addWindowListener(new java.awt.event.WindowAdapter(){@Override public void windowClosing(java.awt.event.WindowEvent e){logout();}});}
    private JPanel sidebar(){JPanel side=new JPanel();side.setPreferredSize(new Dimension(245,0));side.setBackground(new Color(39,93,130));side.setBorder(new EmptyBorder(28,18,24,18));side.setLayout(new BoxLayout(side,BoxLayout.Y_AXIS));JLabel logo=new JLabel("🍽  Cafeteria");logo.setForeground(Color.WHITE);logo.setFont(new Font("SansSerif",Font.BOLD,24));logo.setAlignmentX(Component.CENTER_ALIGNMENT);JLabel small=new JLabel("STAFF PORTAL");small.setForeground(new Color(202,232,255));small.setFont(new Font("SansSerif",Font.BOLD,11));small.setAlignmentX(Component.CENTER_ALIGNMENT);side.add(logo);side.add(Box.createVerticalStrut(5));side.add(small);side.add(Box.createVerticalStrut(35));addNav(side,"⌂  Dashboard",UITheme.BLUE,e->showHome());addNav(side,"🧾  Orders",UITheme.PURPLE,e->showOrders());addNav(side,"🍔  Menu",UITheme.PINK,e->showMenu());addNav(side,"📊  Reports",UITheme.MINT,e->showReports());side.add(Box.createVerticalGlue());UITheme.RoundedButton logout=UITheme.button("↪  Logout",new Color(235,91,91));logout.setAlignmentX(Component.CENTER_ALIGNMENT);logout.setMaximumSize(new Dimension(205,48));logout.addActionListener(e->logout());side.add(logout);return side;}
    private void addNav(JPanel s,String t,Color c,java.awt.event.ActionListener a){UITheme.RoundedButton b=UITheme.button(t,c);b.setAlignmentX(Component.CENTER_ALIGNMENT);b.setMaximumSize(new Dimension(205,48));b.addActionListener(a);s.add(b);s.add(Box.createVerticalStrut(12));}
    private void prepare(String title,String subtitle){content.removeAll();JPanel header=new JPanel(new BorderLayout());header.setOpaque(false);header.setBorder(new EmptyBorder(28,34,18,34));JPanel texts=new JPanel();texts.setOpaque(false);texts.setLayout(new BoxLayout(texts,BoxLayout.Y_AXIS));texts.add(UITheme.title(title,27));texts.add(Box.createVerticalStrut(5));texts.add(UITheme.subtitle(subtitle));header.add(texts,BorderLayout.WEST);JLabel user=new JLabel("👨‍💼  "+staff.getName()+"  •  "+staff.getRole());user.setForeground(UITheme.BLUE);user.setFont(new Font("SansSerif",Font.BOLD,13));header.add(user,BorderLayout.EAST);content.add(header,BorderLayout.NORTH);}
    private void showHome(){prepare("Staff Dashboard 📊","Manage the cafeteria from one colorful workspace.");JPanel body=new JPanel(new GridLayout(2,2,18,18));body.setOpaque(false);body.setBorder(new EmptyBorder(0,34,30,34));body.add(stat("🧾","Total Orders",String.valueOf(app.orderManager.getTotalOrders()),UITheme.BLUE));body.add(stat("💰","Revenue",String.format("EGP %.2f",app.orderManager.getTotalRevenue()),UITheme.MINT));body.add(stat("🍔","Menu Items",String.valueOf(app.menuManager.getAllMenuItems().size()),UITheme.PINK));body.add(stat("⭐","Points Awarded",String.valueOf(app.loyaltyManager.getTotalPointsAwarded()),UITheme.YELLOW));content.add(body,BorderLayout.CENTER);content.revalidate();}
    private JPanel stat(String i,String l,String v,Color c){UITheme.RoundedPanel p=new UITheme.RoundedPanel(26,Color.WHITE);p.setBorder(new EmptyBorder(25,25,25,25));p.setLayout(new BorderLayout());JLabel icon=new JLabel(i);icon.setFont(new Font("Segoe UI Emoji",Font.PLAIN,36));JLabel val=UITheme.title(v,26);val.setForeground(c);JLabel lab=UITheme.subtitle(l);JPanel t=new JPanel();t.setOpaque(false);t.setLayout(new BoxLayout(t,BoxLayout.Y_AXIS));t.add(lab);t.add(Box.createVerticalStrut(6));t.add(val);p.add(icon,BorderLayout.WEST);p.add(t,BorderLayout.CENTER);return p;}
    private void showOrders(){prepare("Order Management 🧾","Review orders and update their status.");JPanel list=new JPanel();list.setOpaque(false);list.setLayout(new BoxLayout(list,BoxLayout.Y_AXIS));for(StudentOrder o:app.orderManager.getAllOrders()){UITheme.RoundedPanel card=UITheme.card();card.setMaximumSize(new Dimension(Integer.MAX_VALUE,125));card.setLayout(new BorderLayout(15,5));JPanel info=new JPanel();info.setOpaque(false);info.setLayout(new BoxLayout(info,BoxLayout.Y_AXIS));JLabel id=UITheme.title(o.getOrderId()+"  •  Student: "+o.getStudentId(),17);JLabel st=new JLabel("●  "+o.getStatus());st.setForeground(statusColor(o.getStatus()));st.setFont(new Font("SansSerif",Font.BOLD,13));JLabel items=UITheme.subtitle(itemsText(o));info.add(id);info.add(Box.createVerticalStrut(5));info.add(st);info.add(Box.createVerticalStrut(4));info.add(items);UITheme.RoundedButton update=UITheme.button("Update Status",UITheme.BLUE);update.addActionListener(e->updateStatus(o));JLabel total=new JLabel(String.format("EGP %.2f",o.getTotalPrice()));total.setFont(new Font("SansSerif",Font.BOLD,18));total.setForeground(UITheme.PURPLE_DARK);JPanel east=new JPanel();east.setOpaque(false);east.setLayout(new BoxLayout(east,BoxLayout.Y_AXIS));east.add(total);east.add(Box.createVerticalStrut(10));east.add(update);card.add(info,BorderLayout.CENTER);card.add(east,BorderLayout.EAST);list.add(card);list.add(Box.createVerticalStrut(10));}if(app.orderManager.getAllOrders().isEmpty()){UITheme.RoundedPanel empty=UITheme.card();empty.add(new JLabel("No orders have been placed yet."));list.add(empty);}JScrollPane scroll=new JScrollPane(list);scroll.setBorder(null);scroll.getVerticalScrollBar().setUnitIncrement(16);JPanel wrap=new JPanel(new BorderLayout());wrap.setOpaque(false);wrap.setBorder(new EmptyBorder(0,34,25,34));wrap.add(scroll);content.add(wrap,BorderLayout.CENTER);content.revalidate();}
    private void updateStatus(StudentOrder o){String[] statuses={"Pending","Preparing","Ready for Pickup","Completed"};String selected=(String)JOptionPane.showInputDialog(this,"Choose a new status:","Update "+o.getOrderId(),JOptionPane.PLAIN_MESSAGE,null,statuses,o.getStatus());if(selected!=null){app.orderManager.updateOrderStatus(o.getOrderId(),selected);showOrders();}}
    private void showMenu(){prepare("Menu Management 🍔","Add new food and drinks to the cafeteria menu.");JPanel body=new JPanel(new BorderLayout(15,15));body.setOpaque(false);body.setBorder(new EmptyBorder(0,34,30,34));JPanel list=new JPanel();list.setOpaque(false);list.setLayout(new BoxLayout(list,BoxLayout.Y_AXIS));for(MenuItem item:app.menuManager.getAllMenuItems()){UITheme.RoundedPanel c=UITheme.card();c.setMaximumSize(new Dimension(Integer.MAX_VALUE,82));c.setLayout(new BorderLayout());JPanel info=new JPanel();info.setOpaque(false);info.setLayout(new BoxLayout(info,BoxLayout.Y_AXIS));info.add(UITheme.title(item.getName(),16));info.add(Box.createVerticalStrut(3));info.add(UITheme.subtitle(item.getCategory()+"  •  EGP "+String.format("%.2f",item.getPrice())+"  •  "+item.getPoints()+" points"));c.add(info);list.add(c);list.add(Box.createVerticalStrut(8));}JScrollPane scroll=new JScrollPane(list);scroll.setBorder(null);body.add(scroll,BorderLayout.CENTER);UITheme.RoundedButton add=UITheme.button("＋ Add Menu Item",UITheme.PINK);add.addActionListener(e->addMenuItem());body.add(add,BorderLayout.SOUTH);content.add(body,BorderLayout.CENTER);content.revalidate();}
    private void addMenuItem(){JTextField name=UITheme.textField("Name");JTextField desc=UITheme.textField("Description");JTextField price=UITheme.textField("Price");JTextField category=UITheme.textField("Category");JTextField points=UITheme.textField("Points (50-100)");Object[] fields={"Name",name,"Description",desc,"Price",price,"Category",category,"Points",points};if(JOptionPane.showConfirmDialog(this,fields,"Add Menu Item",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)==JOptionPane.OK_OPTION){try{double p=Double.parseDouble(price.getText().trim());int pts=Integer.parseInt(points.getText().trim());if(name.getText().trim().isEmpty()||desc.getText().trim().isEmpty()||category.getText().trim().isEmpty()||p<=0||pts<50||pts>100)throw new IllegalArgumentException();app.menuManager.addMenuItem(new MenuItem(name.getText().trim(),desc.getText().trim(),p,category.getText().trim(),pts));JOptionPane.showMessageDialog(this,"Menu item added successfully!","Success",JOptionPane.INFORMATION_MESSAGE);showMenu();}catch(Exception ex){JOptionPane.showMessageDialog(this,"Please enter valid values.","Invalid Input",JOptionPane.ERROR_MESSAGE);}}}
    private void showReports(){prepare("Reports & Analytics 📊","A quick overview of cafeteria activity.");JPanel body=new JPanel(new GridLayout(2,2,18,18));body.setOpaque(false);body.setBorder(new EmptyBorder(0,34,30,34));body.add(stat("🧾","Orders",String.valueOf(app.reportService.getTotalOrders()),UITheme.BLUE));body.add(stat("💰","Revenue",String.format("EGP %.2f",app.reportService.getTotalRevenue()),UITheme.MINT));body.add(stat("⭐","Points Awarded",String.valueOf(app.reportService.getPointsAwarded()),UITheme.YELLOW));body.add(stat("🎁","Points Redeemed",String.valueOf(app.reportService.getPointsRedeemed()),UITheme.PINK));content.add(body,BorderLayout.CENTER);content.revalidate();}
    private String itemsText(StudentOrder o){StringBuilder s=new StringBuilder();for(OrderItem i:o.getItems()){if(s.length()>0)s.append("  •  ");s.append(i.getMenuItem().getName()).append(" x").append(i.getQuantity());}return s.toString();}
    private Color statusColor(String s){return switch(s){case "Completed"->UITheme.MINT;case "Ready for Pickup"->UITheme.BLUE;case "Preparing"->UITheme.YELLOW;default->UITheme.PURPLE;};}
    private void logout(){dispose();loginFrame.setVisible(true);}
}
